// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HandsOnTest.DbModels
{
    using System;
    using System.Linq;
    using System.Collections.Generic;

    public partial class Employee
    {
        /// <summary>
        /// Initializes a new instance of the Employee class.
        /// </summary>
        public Employee() { }

        /// <summary>
        /// Initializes a new instance of the Employee class.
        /// </summary>
        public Employee(int? id = default(int?), string name = default(string), string contractTypeName = default(string), int? roleId = default(int?), string roleName = default(string), string roleDescription = default(string), double? hourlySalary = default(double?), double? monthlySalary = default(double?))
        {
            Id = id;
            Name = name;
            ContractTypeName = contractTypeName;
            RoleId = roleId;
            RoleName = roleName;
            RoleDescription = roleDescription;
            HourlySalary = hourlySalary;
            MonthlySalary = monthlySalary;
        }

        public int? Id { get; set; }

        public string Name { get; set; }

        public string ContractTypeName { get; set; }

        public int? RoleId { get; set; }

        public string RoleName { get; set; }

        public string RoleDescription { get; set; }

        public double? HourlySalary { get; set; }
        public double? MonthlySalary { get; set; }

    }
}
